### ISSUE TITLE
Generate site and CV from pdf

### ISSUE THREAD

**Issue by enieber** [station-work/my-profile#1]
How an professional I has one json file with all my profile data
And I wanna genere my site from this data
And generate CV pdf 
And download CV pdf from my website

## Tasks

- [ ] create json with all data
- [ ] generate template website
- [ ] generate site with json based
- [ ] generate pdf with json based
- [ ] download pdf file from website
